sonar.projectKey=scooper4711_chronicle2layout
sonar.organization=scooper4711
sonar.projectName=chronicle2layout

sonar.sources=blueprint2layout,chronicle_extractor,layout_generator,layout_visualizer,scenario_renamer,shared
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/.venv/**,**/node_modules/**,**/__pycache__/**,.hypothesis/**,Legacy_Layouts/**,Scenarios/**,Blueprints/**,modules/**,debug_clips/**,debug_scripts/**
