"""Property-based tests for layout_generator.metadata module.

Uses hypothesis to verify universal properties of metadata rule
matching across randomly generated inputs.
"""

from __future__ import annotations

import re

from hypothesis import given, assume
from hypothesis import strategies as st

from layout_generator.metadata import (
    MatchedMetadata,
    MetadataConfig,
    MetadataRule,
    apply_substitutions,
    match_rule,
)


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Simple literal path segments — these work as regex patterns that match
# themselves, avoiding regex special-character issues.
_path_segment = st.from_regex(r"[a-z][a-z0-9]{0,9}", fullmatch=True)

_path = st.builds(
    lambda parts: "/".join(parts),
    st.lists(_path_segment, min_size=1, max_size=4),
).map(lambda p: p + ".pdf")

_id_template = st.from_regex(r"[a-z][a-z0-9\-]{0,19}", fullmatch=True)
_parent_template = st.from_regex(r"[a-z][a-z0-9\-]{0,19}", fullmatch=True)


def _metadata_rule(pattern: str) -> st.SearchStrategy[MetadataRule]:
    """Build a MetadataRule strategy with a fixed literal pattern."""
    return st.builds(
        MetadataRule,
        pattern=st.just(pattern),
        id=_id_template,
        parent=_parent_template,
    )


# ---------------------------------------------------------------------------
# Property 1: First-match rule semantics
# ---------------------------------------------------------------------------


# Feature: layout-generator, Property 1: First-match rule semantics
@given(
    test_path=_path,
    prefix_rules=st.lists(
        st.tuples(_path_segment, _id_template, _parent_template),
        min_size=0,
        max_size=5,
    ),
    matching_id=_id_template,
    matching_parent=_parent_template,
    suffix_rules=st.lists(
        st.tuples(_path_segment, _id_template, _parent_template),
        min_size=0,
        max_size=5,
    ),
)
def test_first_match_rule_semantics(
    test_path: str,
    prefix_rules: list[tuple[str, str, str]],
    matching_id: str,
    matching_parent: str,
    suffix_rules: list[tuple[str, str, str]],
) -> None:
    """match_rule returns the first matching rule's metadata, ignoring later rules.

    Validates: Requirements 2.7

    Strategy: build an ordered rule list where:
    - prefix rules use patterns that do NOT match the test path
    - one rule uses a pattern guaranteed to match the test path
    - suffix rules may or may not match (doesn't matter)

    The result must always come from the guaranteed-match rule.
    """
    # Build non-matching prefix rules using patterns that won't match
    # the test path. We use "^NOMATCH_<segment>$" which won't match
    # any path generated by _path (those always contain "/" and ".pdf").
    rules: list[MetadataRule] = []
    for segment, rule_id, rule_parent in prefix_rules:
        rules.append(
            MetadataRule(
                pattern=f"^NOMATCH_{segment}$",
                id=rule_id,
                parent=rule_parent,
            )
        )

    # The first matching rule — uses a catch-all pattern
    first_matching_rule = MetadataRule(
        pattern=".*",
        id=matching_id,
        parent=matching_parent,
    )
    rules.append(first_matching_rule)

    # Suffix rules that also match (catch-all) — should be ignored
    for segment, rule_id, rule_parent in suffix_rules:
        rules.append(
            MetadataRule(
                pattern=".*",
                id=rule_id,
                parent=rule_parent,
            )
        )

    config = MetadataConfig(layouts_dir=None, rules=rules)
    result = match_rule(test_path, config)

    assert result is not None
    assert result.id == matching_id
    assert result.parent == matching_parent


# ---------------------------------------------------------------------------
# Strategies for Property 11
# ---------------------------------------------------------------------------

# Literal words used as capture group values — alphanumeric only to avoid
# regex special characters and ensure clean matching.
_capture_word = st.from_regex(r"[a-z]{2,8}", fullmatch=True)


# ---------------------------------------------------------------------------
# Property 11: Regex substitution replaces all valid group references
# ---------------------------------------------------------------------------


# Feature: layout-generator, Property 11: Regex substitution replaces all valid group references
@given(
    words=st.lists(_capture_word, min_size=1, max_size=5),
)
def test_regex_substitution_replaces_valid_references(
    words: list[str],
) -> None:
    """apply_substitutions replaces all valid $k references and leaves invalid ones as literals.

    Validates: Requirements 15.1, 15.2

    Strategy:
    - Generate N literal words as capture group values.
    - Build a regex with N capture groups: (word1)(word2)...(wordN).
    - Build a test string that matches: word1word2...wordN.
    - Build a template containing $0 through $N (all valid) plus $N+1 (invalid).
    - Verify each valid $k is replaced with the correct group value.
    - Verify $N+1 is left as a literal string.
    """
    num_groups = len(words)
    full_match_text = "".join(words)

    # Build regex pattern with one capture group per word
    pattern = "".join(f"({word})" for word in words)
    match = re.match(pattern, full_match_text)
    assert match is not None

    # Build template: "prefix_$0_$1_..._$N_$N+1_suffix"
    invalid_ref = f"${num_groups + 1}"
    parts = [f"${k}" for k in range(num_groups + 1)]
    parts.append(invalid_ref)
    template = "_".join(["prefix"] + parts + ["suffix"])

    result = apply_substitutions(template, match)

    # Build expected: $0 → full match, $1...$N → individual words
    expected_parts = [full_match_text] + words + [invalid_ref]
    expected = "_".join(["prefix"] + expected_parts + ["suffix"])

    assert result == expected
